# Generated by Django 5.2 on 2025-04-28 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("D", "Paid"), ("L", "Late")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"is_merchant": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        limit_choices_to={"is_merchant": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("D", "Paid"), ("L", "Late")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="payments.paymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("plan", "sequence")},
            },
        ),
    ]
