# Generated by Django 5.2 on 2025-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["plan", "status"], name="payments_in_plan_id_0dce4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installment",
            index=models.Index(
                fields=["status", "due_date"], name="payments_in_status_ea9efe_idx"
            ),
        ),
    ]
